# Generated by Django 4.2.6 on 2024-01-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_description_event_eventgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user2event',
            name='hasBeenNotified',
            field=models.BooleanField(default=False),
        ),
    ]
