# Generated by Django 4.2.6 on 2024-01-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isExpired',
            field=models.BooleanField(default=False),
        ),
    ]
